# Generated by Django 3.0.2 on 2020-01-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering')], default='Computer Science and Engineering', max_length=255)),
                ('intake', models.PositiveSmallIntegerField()),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('session', models.CharField(choices=[('2007-2008', '2007-2008'), ('2008-2009', '2008-2009'), ('2009-2010', '2009-2010'), ('2010-2011', '2010-2011'), ('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021')], max_length=50)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('quora', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('stack_overflow', models.URLField(blank=True, null=True)),
                ('skype', models.URLField(blank=True, null=True)),
                ('accounts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jon_from', models.DateField()),
                ('job_to', models.DateField()),
                ('currently', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('institute_type', models.CharField(max_length=255)),
                ('institute_website', models.URLField()),
                ('institute_address', models.TextField()),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.Account')),
            ],
        ),
    ]
