# Generated by Django 3.0.2 on 2020-01-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200119_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='jon_from',
            new_name='job_from',
        ),
    ]
