# Generated by Django 3.0.2 on 2020-02-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200123_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='user',
        ),
    ]
